input {
  # heartbeat {
    # interval => 10
    # message => "logstash alive"
  # }
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.7.10.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/mydb"
    jdbc_user => "myuser"
    jdbc_password => "mypassword"
    statement => "SELECT * FROM test_table"
    # schedule => "* * * * *" # Optional: Runs every minute
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "postgres_data_index"
  }

  stdout {
    codec => rubydebug
  }
}
