input {
  heartbeat {
    interval => 10
    message => "logstash alive"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "heartbeat-index"
  }

  stdout {
    codec => rubydebug
  }
}
